name: React-S3 빌드

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@master
        
      - name: yarn 캐싱
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        
      - name: 의존 파일 설치
        working-directory: ./react-social
        run: |
             yarn install 

      - name: React Build 작업
        working-directory: ./react-social
        run: | 
          yarn build
        env:
         CI: ""
      
      - name: S3에 배포하기 
        working-directory: ./react-social
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
             build s3://bomnae-static/front/ \
                --region ap-northeast-2
