name: React-S3 빌드

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@master
        
      - name: node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: 의존 파일 설치
        working-directory: ./react-social
        run: |
             yarn install 

      - name: React Build 작업
        working-directory: ./react-social
        run: | 
          yarn upgrade && yarn run build
      
      - name: S3에 배포하기 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync \
            --recursive \
            --region ap-northeast-2 \
            build s3://bomnae-static/front/ # 자신의 레포지토리로 변경해주세요.
